lightbend/kalix-javascript-sdk

.circleci/config.yml, .gitignore, build/license.json
Also enable CircleCI with GitHub Checks for this repo, and add secrets for publishing.
=> ci: add initial CircleCI config

sdk/settings.js
Keep in sync with framework for a bit longer.
=> bump: update framework version to 0.7.0-beta.8

.circleci/config.yml, samples/js-eventsourced-shopping-cart/shoppingcart_api.proto, samples/js-eventsourced-shopping-cart/shoppingcart_domain.proto, samples/js-valueentity-shopping-cart/shoppingcart_api.proto, samples/js-valueentity-shopping-cart/shoppingcart_domain.proto, sdk/settings.js
=> bump: update framework version to 0.7.0-beta.9

sdk/settings.js, sdk/src/akkaserverless.js
Refs #21
Draft until discovery protocol change is available https://github.com/lightbend/akkaserverless-framework/pull/714
=> fix: delay SDK shutdown until proxy has signalled that it terminated

sdk/integration-test/integration-testkit-test.js, sdk/src/command-helper.js, sdk/src/event-sourced-entity-support.js, sdk/src/replicated-entity-support.js, sdk/src/value-entity-support.js, sdk/test/crdt-handler-test.js, sdk/test/example.proto, tck/event-sourced-entity.js, tck/value-entity.js
Based on the refactoring in #42 finally got it passing the tests! 🎉
=> Support async user functions

package.json, sdk/.mocharc.json, sdk/package-lock.json, sdk/package.json, sdk/src/akkaserverless.js, sdk/src/package-info.ts, sdk/src/replicated-data/gset.js, sdk/src/replicated-data/ormap.js, sdk/src/replicated-data/orset.js, sdk/src/replicated-entity.js, sdk/test/package-info.test.ts, sdk/tsconfig.json
This is an initial setup to be able to work with TS in this codebase.
I have had to remove a few JSDoc annotations to get it working (thanks @janory !).
=> Ts baby steps

sdk/bin/download-protoc.js, sdk/package-lock.json, sdk/package.json
Low hanging fruit:
this removes a bunch of warnings.
=> Remove deprecated 'request' package

docs/Makefile, samples/js-valueentity-shopping-cart/proto/shoppingcart_api.proto, samples/js-valueentity-shopping-cart/proto/shoppingcart_domain.proto
Add Antora tags to source snippets for developer.lightbend.com/docs/akka-serverless/javascript/proto.html from validated Javascript SDK sources.﻿
=> docs: tags for reference in proto.adoc

sdk/package.json
This replaces the TS generated types with the one from JSDocs
=> Use types from JSDocs for now

npm-js/create-akkasls-entity/template/base/package.json, samples/valueentity-counter/package.json
Follow up from:
https://typesafe.slack.com/archives/CQUASEUDV/p1625068565235800
=> Remove un-necessary dependencies

docs/src/modules/javascript/pages/kickstart.adoc
add info for unit testing, resolves #82
to Resolve Doc integration testing for JS #715 from old doc repo
=> add info for unit testing

sdk/.gitignore, sdk/bin/compile-protobuf.sh, sdk/package.json, sdk/src/effect-serializer.js, sdk/test/effect-serializer-test.js
This is more preparation work for bigger refactorings.
=> Test EventSerializer

sdk/src/akkaserverless.ts
Missed this call during the switch to TS.
Thanks @pvlugter for noticing!
@johanandren can I ask you to double-check this feature?
=> Restore proxyTerminatedLogic call

sdk/package.json, sdk/src/action.js, sdk/src/akkaserverless.ts, sdk/src/event-sourced-entity.js, sdk/src/value-entity.js, sdk/test/akkaserverless.test.ts
List of headers to be forwarded in component options.
Manually verified against the updated proxy.
This is waiting on a release of proxy with lightbend/akkaserverless-framework#729 merged.
=> perf/fix: selective header forwarding to user function 

docs/src/modules/developing/pages/development-process-js.adoc
This one is short and sweet. No docker fixes to make - but a couple of fixes I made that are worth merging up.
=> JS SDK Docs - docker fixes

codegen/build.sbt, codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-akkasls-entity/template/base/docker-compose.yml, samples/js-eventsourced-shopping-cart/docker-compose.yml, samples/js-replicated-entity-example/replicated-entity-example.js, samples/js-replicated-entity-example/replicated_entity_example.proto, samples/js-valueentity-shopping-cart/docker-compose.yml, samples/valueentity-counter/docker-compose.yml, sdk/index.js, sdk/settings.js, sdk/src/akkaserverless.ts, sdk/src/replicated-data/index.js, sdk/src/replicated-entity-support.js, sdk/src/replicated-entity.js, sdk/test/replicated-entity-handler-test.js, tck/replicated-entity.js
Update to beta.14, with changes to replicated entities: write consistency setting moved and streamed responses removed.
Also currently includes #130, so that all the SDK tests run.
Refs https://github.com/lightbend/akkaserverless-java-sdk/issues/47
Refs https://github.com/lightbend/akkaserverless-framework/issues/744
=> bump: update to framework 0.7.0 beta.14

docs/src/modules/javascript/pages/views.adoc, docs/src/modules/javascript/partials/views.adoc
Following on to fixes for #119 and #120, this addresses review comments from @pvlugter that didn't get pushed last week. Apparently my push failed. This redoes it.
=> View part 2

samples/js-customer-registry/README.md, samples/js-customer-registry/customer-event-sourced-entity.js, samples/js-customer-registry/customer-event-sourced-view.js, samples/js-customer-registry/customer-value-entity.js, samples/js-customer-registry/customer_api.proto, samples/js-customer-registry/customer_domain.proto, samples/js-customer-registry/customer_view.proto
Refs #108. Update the customer registry sample used for views with a change address command and address changed event, which is ignored by the views.
=> doc: update customer registry sample with ignored event for views

docs/src/modules/javascript/pages/proto.adoc
=> doc: add example of multi field entity key

docs/src/modules/javascript/pages/index.adoc
Fixes #148. Related to feature: https://github.com/lightbend/akkaserverless-docs/issues/813
=> doc: link to support policy

docs/src/modules/javascript/pages/views.adoc, samples/js-customer-registry/customer_view.proto
Fixes #108 Uses the code provided in #150
=> doc: show how to ignore events for views

npm-js/akkasls-scripts/README.md
Fixed a typo, and links now point to the proper place.
=> Tweak link in akkasls-scripts/README.md

docs/Makefile, docs/src/modules/javascript/examples/action/src/action.ts, docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.js, docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.ts, docs/src/modules/javascript/examples/test/gettingstarted/index.ts, docs/src/modules/javascript/examples/value-entity/src/shoppingcart.ts, docs/src/modules/javascript/pages/actions.adoc, docs/src/modules/javascript/pages/eventsourced.adoc, docs/src/modules/javascript/pages/index.adoc, docs/src/modules/javascript/pages/kickstart.adoc, docs/src/modules/javascript/pages/serialization.adoc, docs/src/modules/javascript/pages/value-entity.adoc, docs/src/modules/javascript/pages/views.adoc, samples/js/js-customer-registry/index.js, samples/ts/ts-customer-registry/integration-test/customer-registry-test.ts, samples/ts/ts-customer-registry/src/customer-event-sourced-view.ts, samples/ts/ts-customer-registry/src/customer-value-entity-view.ts, samples/ts/ts-customer-registry/src/index.ts, samples/ts/ts-valueentity-counter/src/counter.ts, samples/ts/ts-valueentity-counter/src/index.ts
Resolves https://github.com/lightbend/akkaserverless-javascript-sdk/issues/174.
=> feat: add TS snippets to the docs

.circleci/config.yml, docs/src/modules/javascript/pages/kickstart.adoc, npm-js/create-akkasls-entity/template/base/.dockerignore, npm-js/create-akkasls-entity/template/base/README.md, npm-js/create-akkasls-entity/template/base/docker-compose.linux.yml, npm-js/create-akkasls-entity/template/base/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/.dockerignore, samples/js/js-eventsourced-shopping-cart/README.md, samples/js/js-eventsourced-shopping-cart/docker-compose.linux.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/.dockerignore, samples/js/js-valueentity-shopping-cart/README.md, samples/js/js-valueentity-shopping-cart/docker-compose.linux.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/.dockerignore, samples/js/valueentity-counter/README.md, samples/js/valueentity-counter/docker-compose.linux.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/.dockerignore, samples/ts/ts-eventsourced-shopping-cart/README.md, samples/ts/ts-eventsourced-shopping-cart/docker-compose.linux.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-valueentity-counter/.dockerignore, samples/ts/ts-valueentity-counter/README.md, samples/ts/ts-valueentity-counter/docker-compose.linux.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/.dockerignore, samples/ts/ts-valueentity-shopping-cart/README.md, samples/ts/ts-valueentity-shopping-cart/docker-compose.linux.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml
Refs https://github.com/lightbend/akkaserverless-java-sdk/pull/436
Single docker compose file for all
=> fix: simplify local development

docs/src/modules/javascript/pages/index.adoc
=> chore: Fixed install command in docs 

docs/bin/bundle.sh
Resolves #205. Use a `json` node utility to check and update the `package.json` in the bundled quickstarts before zipping.
=> fix: update sdk version in quickstart bundles

samples/js/js-customer-registry/.bundleignore, samples/js/js-eventsourced-shopping-cart/.bundleignore, samples/ts/ts-customer-registry/.bundleignore, samples/ts/ts-eventsourced-shopping-cart/.bundleignore
* exclude all hidden such as .idea .DS_Store and such
Refs lightbend/akkaserverless-docs#1043
=> Exclude more files from quickstart bundles

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-akkasls-entity/template/base/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json, sdk/src/event-sourced-entity-support.js, sdk/test/akkaserverless.test.ts
This required implementing the request snapshot message.
=> feat: upgraded framework version to 0.8.0

sdk/src/jwt-claims.ts, sdk/src/metadata.ts, sdk/test/metadata.test.ts
This depends on #220 being merged first.
This adds JWT claims metadata support.
=> feat: added jwt claim metadata support

docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.js, docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.ts, docs/src/modules/javascript/examples/value-entity/src/shoppingcart.js, docs/src/modules/javascript/examples/value-entity/src/shoppingcart.ts, samples/js/js-eventsourced-shopping-cart/src/shoppingcart.js, samples/js/js-valueentity-shopping-cart/src/shoppingcart.js, samples/ts/ts-eventsourced-shopping-cart/src/shoppingcart.ts, samples/ts/ts-valueentity-shopping-cart/src/shoppingcart.ts
Aligns with https://github.com/lightbend/akkaserverless-java-sdk/pull/220﻿
Refs https://github.com/lightbend/akkaserverless-javascript-sdk/issues/159
=> chore: more meaningful error message

samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json
Revert some accidental change that sneaked in #226
=> chore: use fix sdk version in ts-valueentity-counter

codegen/build.sbt, npm-js/create-akkasls-entity/template/base/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
=> chore: upgrade to proxy v0.8.5 (take 2)

codegen/build.sbt, codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-akkasls-entity/template/base/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
References https://github.com/lightbend/akkaserverless-framework/issues/1060
=> chore: upgrade to proxy v0.8.6

docs/src/modules/javascript/pages/proto.adoc
See: https://github.com/lightbend/akkaserverless-docs/issues/1136
=> docs: generated entity keys

docs/src/modules/javascript/partials/topic-eventing.adoc, samples/js/js-doc-snippets/proto/com/example/json/json_api.proto, samples/js/js-doc-snippets/src/myservice.js, sdk/bin/download-protoc.js, sdk/src/action-support.js, sdk/test/action-handler-test.js, sdk/test/example.proto
=> feat: Support emitting JSON to topics

.circleci/config.yml, sdk/index.js, sdk/src/metadata.jsdoc, sdk/src/view-support.js
Cherry picking the metadata fix into the rename branch
References #272
=> forward port of #272 

docs/Makefile
Refs https://github.com/lightbend/kalix/issues/6433
=> rename: publish kalix docs to docs/current-kalix

docs/src/modules/javascript/pages/views.adoc
Refs https://github.com/lightbend/kalix-proxy/issues/1335. Same docs as https://github.com/lightbend/akkaserverless-java-sdk/pull/897. Only for `kalix-main`.
=> docs: new view features

sdk/index.js, sdk/src/cloudevent.jsdoc, sdk/src/jwt-claims.jsdoc, sdk/src/jwt-claims.ts, sdk/src/kalix.jsdoc, sdk/src/kalix.ts, sdk/src/metadata.jsdoc, sdk/src/metadata.ts, sdk/src/reply.jsdoc, sdk/src/reply.ts, sdk/test/metadata.test.ts, sdk/test/reply.test.ts
=> Forward port of missing TS signatures

sdk/src/command-helper.ts, sdk/src/command.jsdoc, sdk/src/command.ts, sdk/src/effect-serializer.ts, sdk/src/effect.ts, sdk/src/metadata.ts, sdk/test/effect-serializer.test.ts, sdk/test/metadata.test.ts
Refs #293. Draft, builds on #295.
=> chore: convert command helper to TypeScript

samples/js/js-eventsourced-shopping-cart/package.json
manually released
fixes https://github.com/lightbend/kalix/issues/6552
=> released js-eventsourced-shopping-cart

samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
Ran `samples/bin/update.sh` as instructed by the release checklist
=> chore: samples update

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---feature-request.md
=> chore: update github issue template labels

samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
=> bump: update samples to 1.0.0-M6 release

.circleci/config.yml
=> rename: re-enable docs link validation

codegen/build.sbt, codegen/js-gen-cli/src/it/resources/application.conf, docs/config/validate-links.json, docs/src/modules/javascript/pages/developer-tools.adoc, npm-js/create-kalix-entity/template/base/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml
References https://github.com/lightbend/kalix-proxy/issues/1485
=> bump: Kalix Proxy 1.0.10

npm-js/create-kalix-entity/template/base-js/jsconfig.json, samples/js/js-doc-snippets/jsconfig.json, samples/js/js-eventsourced-shopping-cart/jsconfig.json, samples/js/js-valueentity-shopping-cart/jsconfig.json, samples/js/valueentity-counter/jsconfig.json
Just some reformatting to 2-space indentation, as used elsewhere.
=> chore: reindent jsconfig.json in template

samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
https://github.com/lightbend/kalix-javascript-sdk/issues/367#issuecomment-1166687102
=> chore: bump samples to new sdk version 1.0.0-M10

.circleci/config.yml, docs/Makefile, docs/src/modules/javascript/pages/quickstart/cr-value-entity-typescript.adoc, samples/ts/ts-customer-registry-quickstart/.bundleignore, samples/ts/ts-customer-registry-quickstart/.dockerignore, samples/ts/ts-customer-registry-quickstart/.gitignore, samples/ts/ts-customer-registry-quickstart/Dockerfile, samples/ts/ts-customer-registry-quickstart/README.md, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/integration-test/customer.test.ts, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry-quickstart/proto/customer_api.proto, samples/ts/ts-customer-registry-quickstart/proto/customer_domain.proto, samples/ts/ts-customer-registry-quickstart/proto/kalix_policy.proto, samples/ts/ts-customer-registry-quickstart/src/customer.ts, samples/ts/ts-customer-registry-quickstart/src/index.ts, samples/ts/ts-customer-registry-quickstart/test/customer.test.ts, samples/ts/ts-customer-registry-quickstart/tsconfig.json
=> docs: add new quickstart for customer registry in typescript

samples/js/js-customer-registry-quickstart/package.json, samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-shopping-cart-quickstart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-shopping-cart-quickstart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
=> bump: update samples to 1.0.0

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json, sdk/test/kalix.test.ts
References [Kalix Proxy 1.0.15](https://github.com/lightbend/kalix-proxy/issues/1605)
=> chore: upgrade Kalix Proxy to 1.0.15

samples/js/js-customer-registry-quickstart/package.json, samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-shopping-cart-quickstart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-shopping-cart-quickstart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
Refs #407. Run `samples/bin/update.sh`.
=> bump: update samples to 1.0.2

docs/src/modules/javascript/pages/value-entity.adoc
References (https://github.com/lightbend/kalix-docs/issues/1474)
=> fix: changing 'file' to 'codegen'

CONTRIBUTING.md, bin/create-local-dependencies.sh
It took me more time than expected to understand how we build the Javascript images in order to use a local SDK. I created this script for future reference.
=> chore: scripting how to test local SDK in Kubernetes.

sdk/src/grpc-util.ts, sdk/src/kalix.ts
References https://github.com/lightbend/kalix-proxy/issues/1469 and depends on https://github.com/lightbend/kalix-proxy/pull/1599
Continuation of https://github.com/lightbend/kalix-javascript-sdk/pull/396
=> feat: Avoiding the mesh

codegen/js-gen/src/main/scala/io/kalix/codegen/js/SourceGenerator.scala
References https://github.com/lightbend/kalix-javascript-sdk/issues/404
=> Fix codegen windows paths

samples/js/js-customer-registry-quickstart/package.json, samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-shopping-cart-quickstart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-shopping-cart-quickstart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
=> chore: updating samples to 1.0.3

.github/release-issue-template.md
Adding some rewording and making sure my understanding of the kalix-docs release is correct. It may need some other clarification otherwise.
=> chore: Rewording template

.circleci/config.yml
References https://github.com/lightbend/kalix/issues/7448
=> ci: run Fossa once per weekday

docs/src/modules/javascript/pages/access-control.adoc, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, testkit/integration-test/integration-testkit.test.ts
References https://github.com/lightbend/kalix/issues/7783
=> fix: disable ACL in dev-mode

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
References https://github.com/lightbend/kalix-proxy/releases/tag/v1.0.26
=> chore: Bump Kalix Proxy 1.0.26

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
https://github.com/lightbend/kalix-proxy/issues/1727
=> chore: Bump proxy to 1.0.28

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
Refs https://github.com/lightbend/kalix-proxy/issues/1776
=> bump: kalix-proxy 1.0.29

codegen/js-gen-cli/src/it/resources/application.conf, npm-js/create-kalix-entity/template/base-common/docker-compose.yml, samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, sdk/config.json
References https://github.com/lightbend/kalix-proxy/issues/1792
=> chore: bump proxy version to 1.0.31

.eslintrc.js, package-lock.json, package.json
8.33 is what is currently available for macOS through Homebrew
=> bump: Eslint 8.3

.circleci/config.yml, .eslintrc.js, sdk/src/action-support.ts, sdk/src/grpc-util.ts, sdk/src/jwt-claims.ts, sdk/src/kalix.ts, sdk/src/metadata.ts, sdk/src/protobuf-any.ts, sdk/src/protobuf-helper.ts, sdk/src/replicated-data/map.ts, sdk/test/action-handler.test.ts
=> Es-lint errors followup

codegen/build.sbt, codegen/core/src/main/scala/io/kalix/codegen/ModelBuilder.scala, codegen/core/src/test/scala/io/kalix/codegen/ModelBuilderSuite.scala, codegen/js-gen/src/main/scala/io/kalix/codegen/js/ActionServiceSourceGenerator.scala, codegen/js-gen/src/main/scala/io/kalix/codegen/js/EntityServiceSourceGenerator.scala, codegen/js-gen/src/main/scala/io/kalix/codegen/js/ViewServiceSourceGenerator.scala, codegen/js-gen/src/test/scala/io/kalix/codegen/js/TestData.scala, docs/src/modules/javascript/examples/eventing-shopping-cart/proto/product/to_product_popularity.proto, docs/src/modules/javascript/pages/actions-publishing-subscribing.adoc
=> chore: Skip methods for ignore annotated event handlers #382

docs/src/modules/javascript/pages/index.adoc
References https://github.com/lightbend/kalix-proxy/issues/1941
Keeping as draft as this should to be synced with JVM changes.
=> chore: renaming docs section title

.github/workflows/labeler.yml
References 
- https://github.com/lightbend/kalix-jvm-sdk/pull/1549
=> bump(ci): labeler action security updates

.circleci/config.yml, .github/workflows/fossa.yml
References
- https://github.com/lightbend/kalix-jvm-sdk/pull/1589
=> chore: migrate Dependency scanning to GH workflows

docs/src/modules/javascript/pages/quickstart/cr-value-entity-javascript.adoc, docs/src/modules/javascript/pages/quickstart/cr-value-entity-typescript.adoc, docs/src/modules/javascript/pages/quickstart/sc-eventsourced-entity-javascript.adoc, docs/src/modules/javascript/pages/quickstart/sc-eventsourced-entity-typescript.adoc
=> fix: quickstart names

samples/js/js-customer-registry-quickstart/package.json, samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-shopping-cart-quickstart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-shopping-cart-quickstart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
=> chore: update sdk version in samples

CONTRIBUTING.md, docs/Makefile
References #496 and https://github.com/lightbend/kalix-javascript-sdk/issues/494#issuecomment-1572909407
=> docs: update minimal node version to 18

samples/js/js-customer-registry-quickstart/package.json, samples/js/js-customer-registry/package-lock.json, samples/js/js-customer-registry/package.json, samples/js/js-doc-snippets/package-lock.json, samples/js/js-doc-snippets/package.json, samples/js/js-eventsourced-shopping-cart/package.json, samples/js/js-replicated-entity-example/package.json, samples/js/js-replicated-entity-shopping-cart/package-lock.json, samples/js/js-replicated-entity-shopping-cart/package.json, samples/js/js-shopping-cart-quickstart/package.json, samples/js/js-valueentity-shopping-cart/package.json, samples/js/js-views-example/package-lock.json, samples/js/js-views-example/package.json, samples/js/valueentity-counter/package.json, samples/ts/ts-customer-registry-quickstart/package.json, samples/ts/ts-customer-registry/package-lock.json, samples/ts/ts-customer-registry/package.json, samples/ts/ts-eventsourced-shopping-cart/package-lock.json, samples/ts/ts-eventsourced-shopping-cart/package.json, samples/ts/ts-replicated-entity-example/package-lock.json, samples/ts/ts-replicated-entity-example/package.json, samples/ts/ts-replicated-entity-shopping-cart/package-lock.json, samples/ts/ts-replicated-entity-shopping-cart/package.json, samples/ts/ts-shopping-cart-quickstart/package.json, samples/ts/ts-valueentity-counter/package-lock.json, samples/ts/ts-valueentity-counter/package.json, samples/ts/ts-valueentity-shopping-cart/package-lock.json, samples/ts/ts-valueentity-shopping-cart/package.json, samples/ts/ts-views-example/package-lock.json, samples/ts/ts-views-example/package.json
=> bump: update samples to latest sdk 1.1.0

.github/labeler.yml
References
- https://github.com/lightbend/kalix/issues/9895
=> chore: kalix-runtime labels

docs/src/modules/developing/pages/development-process-js.adoc, docs/src/modules/javascript/pages/kickstart.adoc
Closes: #532
Refs: lightbend/kalix-docs#2018
=> docs: fix broken links to Setting Up section

samples/js/js-customer-registry-quickstart/docker-compose.yml, samples/js/js-customer-registry/README.md, samples/js/js-customer-registry/docker-compose.yml, samples/js/js-doc-snippets/docker-compose.yml, samples/js/js-eventsourced-shopping-cart/docker-compose.yml, samples/js/js-replicated-entity-example/docker-compose.yml, samples/js/js-replicated-entity-shopping-cart/README.md, samples/js/js-replicated-entity-shopping-cart/docker-compose.yml, samples/js/js-shopping-cart-quickstart/docker-compose.yml, samples/js/js-valueentity-shopping-cart/docker-compose.yml, samples/js/js-views-example/docker-compose.yml, samples/js/valueentity-counter/docker-compose.yml, samples/ts/ts-customer-registry-quickstart/docker-compose.yml, samples/ts/ts-customer-registry/README.md, samples/ts/ts-customer-registry/docker-compose.yml, samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml, samples/ts/ts-replicated-entity-example/docker-compose.yml, samples/ts/ts-replicated-entity-shopping-cart/README.md, samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml, samples/ts/ts-shopping-cart-quickstart/docker-compose.yml, samples/ts/ts-valueentity-counter/README.md, samples/ts/ts-valueentity-counter/docker-compose.yml, samples/ts/ts-valueentity-shopping-cart/docker-compose.yml, samples/ts/ts-views-example/docker-compose.yml, sdk/bin/prepare.sh
References
- https://github.com/lightbend/kalix/issues/9895
- https://github.com/lightbend/kalix-jvm-sdk/issues/1910
=> Use USER_SERVICE_ instead of USER_FUNCTION_
