lightbend/kalix-javascript-sdk

- sdk/bin/version.sh
When determining the SDK version, no longer use the Akka Serverless framework base version. Use regular dynamic versioning.
> build: remove the framework base version from dynamic versions

- sdk/package.json
Oops. Missed file in the packaging. Not picked up by testing, which uses the SDK locally and not packaged.
> build: add settings.js to package

- samples/js-customer-registry/Dockerfile
- samples/js-eventsourced-shopping-cart/Dockerfile
- samples/js-replicated-entity-example/Dockerfile
- samples/js-valueentity-shopping-cart/Dockerfile
- samples/js-views-example/Dockerfile
- tck/Dockerfile
Noticed by CI when publishing TCK docker image. If building from a clean repo, the SDK needs `npm run prepare` to be run explicitly when using `npm ci` in the docker build.
I'll publish the TCK docker image for `0.7.0-beta.7` manually. Should work fine for next release.
> build: fix sdk build within docker builds

- sdk/src/akkaserverless.js
fixes #9 
Added an extra check to make sure that only when there's an actual error code we call the `docLinkFor()` method
> fix: only call doclinkfor when there is a code

- docs/.examplesignore
- docs/Makefile
The `js-customer-registry` sample app is already annotated with doc tags, and has been manually copied into the docs repo. Copy the sources for this sample into the doc examples automatically instead.
Already published this manually to the `docs/current` branch.
> doc: start copying doc examples directly from sample apps

- sdk/src/protobuf-any.js
- sdk/test/protobuf-any-test.js
Noticed when sending requests with `grpcurl` and empty body. These arrive as protobuf any with undefined values, which would crash the service. Default to an empty array/buffer and check that these are deserialised as an empty message.
> fix: deserialize protobuf any with undefined values (no bytes)

- .gitignore
- sdk/.gitignore
- sdk/.npmrc
- sdk/bin/prepare.sh
- sdk/package-lock.json
- sdk/package.json
- sdk/src/action-support.js
- sdk/src/action.js
- sdk/src/akkaserverless.js
- sdk/src/command-helper.js
- sdk/src/event-sourced-entity-support.js
- sdk/src/event-sourced-entity.js
- sdk/src/integration-testkit.js
- sdk/src/protobuf-any.js
- sdk/src/replicated-data/gset.js
- sdk/src/replicated-data/ormap.js
- sdk/src/replicated-data/orset.js
- sdk/src/replicated-data/vote.js
- sdk/src/replicated-entity.js
- sdk/src/reply.js
- sdk/src/value-entity-support.js
- sdk/src/value-entity.js
- sdk/src/view.js
Fixes this issue https://github.com/lightbend/akkaserverless-framework/issues/689.
In order to make the JSDoc -> .d.ts generation work, I had to change a few things:
- fix JSDoc annotations/comments where the generator yielded an error (please verify if the changes make sense)
- use a patched tsd-jsdoc generator because of this issue: https://github.com/englercj/tsd-jsdoc/issues/89
- [fork and create a package](https://github.com/janory/tsd-jsdoc/packages/833291) from [englercj's PR](https://github.com/englercj/tsd-jsdoc/pull/144/files#diff-9af2ecc9ea9c57456a81fadd6bf93a6d974c4aa1421e8bf912ce080d70be4fcb)
- even the forked version didn't work fully so had to [monkey patch it](https://github.com/janory/tsd-jsdoc/commit/d5ebc54eb6e624e0bc7e56a8f73f27296a2dada3) before publishing
- add the …
> feat: basic type definition generation from jsdoc

- .circleci/config.yml
Remove the sudo commands from CI builds, which are likely causing permission issues.
Prefer [`npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci) for the SDK. Use `nvm` for node version management.
I've left these linked SDK tests as standalone, but we could move the `npm link` up to the sdk build and test command at some point.
> ci: remove sudo commands from circleci builds

- sdk/package-lock.json
At some point we switched to package lock v2 for npm 7. When I switch to npm 7, it fails with node-gyp errors though. This is resolved (for me at least) by running an `npm update` to have latest versions in the package-lock. Let's check this still works in CI too, where the node 14 docker image has npm 6.
> chore: run npm update on sdk

- docs/Makefile
Rename from `js-services` to `javascript`. Keep a copy at the old location during the transition. Already published to the [`docs/current` branch](https://github.com/lightbend/akkaserverless-javascript-sdk/tree/docs/current/docs/build/src/managed/modules).
> chore: rename docs module from js-services to javascript

- sdk/src/action-support.js
- sdk/src/effect-serializer.js
- sdk/test/action-handler-test.js
Add a deprecation warning for context.effect in actions, as for entities.
Add action handler tests for effects, including the deprecation warning.
Also rename `command` context/handler to `action` context/handler in the warnings, as we're not referring to command handlers for actions any longer, just handlers.
Resolves https://github.com/lightbend/akkaserverless-framework/issues/639
> fix: add deprecation for action context effects

- .circleci/config.yml
Resolves #7. Update the sample testing to install the generated package. This also avoids any permission issues with linking that were there before. I've left the integration tests still using the linking approach.
> ci: test npm pack and install when testing samples

- .circleci/config.yml
- sdk/package-lock.json
Related to #32 
Do we aim for a stricter check?
e.g. should I remove `--omit dev` ?
> Run npm audit in CI

- sdk/package.json
Resolves #50. Alternative fix to #45. I've checked this by publishing `0.7.0-beta.10`, which failed to publish in CI and works with this config override now.
> fix: always publish to npmjs registry

- docs/Makefile
Now that https://github.com/lightbend/akkaserverless-docs/pull/748 is merged, we should be able to switch back to `docs/current` branch again, and then also update in akkaserverless-docs.
> doc: switch back to publishing to docs/current branch

- codegen/js-gen/src/main/scala/com/lightbend/akkasls/codegen/js/ActionServiceSourceGenerator.scala
- codegen/js-gen/src/main/scala/com/lightbend/akkasls/codegen/js/EntityServiceSourceGenerator.scala
- codegen/js-gen/src/main/scala/com/lightbend/akkasls/codegen/js/SourceGenerator.scala
- codegen/js-gen/src/main/scala/com/lightbend/akkasls/codegen/js/ViewServiceSourceGenerator.scala
- codegen/js-gen/src/test/scala/com/lightbend/akkasls/codegen/js/ActionServiceSourceGeneratorSuite.scala
- codegen/js-gen/src/test/scala/com/lightbend/akkasls/codegen/js/EntityServiceSourceGeneratorSuite.scala
- codegen/js-gen/src/test/scala/com/lightbend/akkasls/codegen/js/SourceGeneratorSuite.scala
- codegen/js-gen/src/test/scala/com/lightbend/akkasls/codegen/js/ViewServiceSourceGeneratorSuite.scala
This is the backport of the last PR in codegen that missed the migration to the JS SDK
> Add comments specifying which files are generated

- .circleci/config.yml
The release is changing `package.json` and the "next" publishing becomes "dirty".
e.g.:
https://www.npmjs.com/package/@lightbend/create-akkasls-entity/v/0.30.0-beta.1-0-add67021-dev
> Prevent dirty versions when releasing npm packages

- codegen/build.sbt
- codegen/project/plugins.sbt
Codegen shouldn't be depending on the Java SDK for the akkaserverless annotations. Compile the SDK protocol directly instead, with the akkaserverless version for the protocol/proxy.
Also including in #89 to check the bump to the new protocol.
> build: compile SDK protocol directly for codegen

- docs/src/modules/javascript/pages/kickstart.adoc
- docs/src/modules/javascript/partials/running-service-locally.adoc
Updated the docs to reflect the correct stylization of macOS (lowercase m, uppercase OS)
> chore(docs): fix correct stylization of macOS

- sdk/src/akkaserverless.ts
- sdk/test/akkaserverless.test.ts
Add doc links for the new error codes for eventing validation for entity types (https://github.com/lightbend/akkaserverless-framework/pull/773). Note that the docs currently only cover subscribing to event sourced entities (doc issue #103).
Also use a newline before the doc link — which creates tidier formatting, and more similar to the Java SDK.
> Add doc links for entity eventing error codes

- sdk/src/akkaserverless.ts
- sdk/test/akkaserverless.test.ts
Small correction to error reporting. Make it from `Akka Serverless system` rather than `Akka system`. Same as Java SDK now.
> fix: report errors as being from Akka Serverless system

- docs/Makefile
With the new doc builder using antora 3 (alpha pre-release), the build can be failed on warnings or errors. Previously these would only be logged and the build succeed.
So this covers includes not found:
```
[01:15:58.779] ERROR (asciidoctor): target of include not found: example$some/unknown/file.js
file: /antora/docs/src/modules/javascript/pages/value-entity.adoc:26
source: /antora (refname: fail-unresolved-includes <worktree>, start path: docs/src)
make: *** [dev-html] Error 1
```
Or callouts not found:
```
[01:15:58.789] WARN (asciidoctor): no callout found for <1>
file: /antora/docs/src/modules/javascript/pages/value-entity.adoc:29
source: /antora (refname: fail-unresolved-includes <worktree>, start path: docs/src)
```
> doc: fail warnings and errors, like unresolved includes

- tck/Dockerfile
Update the docker build for the tck after the changes in #77.
And when node runs as root it won't run other task dependencies (so install doesn't run prepare, pack doesn't run prepack, and so on). Rather than run these tasks explicitly, switch to running as the node user for the build parts as well. Still in separate steps for cached builds.
We don't test anything with these docker images (including the samples), maybe something to follow up on, or otherwise just something to deal with when we update the use of these elsewhere.
> tck: fix docker build for tck image

- tck/index.js
- tck/view.js
The proxy will have eventing source validation, so the view in the TCK needs an existing entity as its source now.
See https://github.com/lightbend/akkaserverless-framework/pull/774 and https://github.com/lightbend/akkaserverless-framework/pull/773
> tck: add view source entity

- .circleci/config.yml
The macOS native image build failed for 0.31.0 release, as sbt was running with openjdk 16:
https://app.circleci.com/pipelines/github/lightbend/akkaserverless-javascript-sdk/426/workflows/64b38cfe-fd38-4729-bae4-488022d479de/jobs/2037
This must have changed at some point since last release, where sbt depends on brew-installed openjdk by default, and this is now JDK 16. There are a few ways to fix this. There is an AdoptOpenJDK 11 install with the OS already. And JAVA_HOME can be specified. I've opted to link openjdk@11 as the default openjdk, and not install the openjdk dependency for sbt, so that using the sbt command as is will run with the explicitly installed openjdk by default.
For 0.31.0, I've manually published the native image for macOS (from the CI machine, with rerun job with …
> ci: fix java versions for macOS builds

- sdk/.gitignore
- sdk/bin/compile-protobuf.sh
- sdk/package.json
Since #92 looks like we stopped running all the tests. https://github.com/lightbend/akkaserverless-javascript-sdk/pull/92/commits/46ba10723c1514b9bde4222dfb59a8e763fcd3ff ended up updating so that only the replicated data tests were [running](https://app.circleci.com/pipelines/github/lightbend/akkaserverless-javascript-sdk/380/workflows/27859c17-21a9-467c-9031-fd27f8c116e2/jobs/1697) -> `77 passing`.
This reverts some of the changes for compiling the test protobufs, and rather than trying to include particular tests, this uses mocha's exclude/ignore to not run compiled proto as tests.
I'll check this works in CI too, but all tests running again -> `149 passing`
> test: fix test setup so that they all run again

- sdk/src/action.js
- sdk/src/event-sourced-entity.js
- sdk/src/value-entity.js
Since the TS' type generation is currently based on the JSDoc annotations, this fix is necessary in order to be able to correctly generate the types for the options fields.
> fix: set default value for forwardHeaders in JSDoc

- docs/src/modules/javascript/pages/views.adoc
- samples/js-customer-registry/customer_domain.proto
- samples/js-customer-registry/customer_view.proto
Fixes issue #97. Note, I'm marking this as a draft because it involves both source code and doc and I am not able to build it locally on my machine to check it. 
I also did not add all of the proto file to each example because we are using the same proto file to illustrate all of the different types of views. Instead, I just added the declarations. Are these additions enough so that a user copying them from the doc could create their own views (of each different type)?
> enhancement: show fuller proto files

- sdk/package-lock.json
Other PR builds will keep failing until these version bumps are applied.
> bump: apply npm audit fix for high severity vulnerabilities

- samples/js-replicated-entity-example/replicated-entity-example.js
- sdk/index.js
- sdk/src/event-sourced-entity.js
- sdk/src/replicated-entity.js
- sdk/src/value-entity.js
- tck/replicated-entity.js
Reported that the `entityPassivationStrategy` was missing from the entity options.
> fix: add type declarations for entity passivation strategy

- codegen/build.sbt
- codegen/js-gen-cli/src/it/resources/application.conf
- npm-js/create-akkasls-entity/template/base/docker-compose.yml
- samples/js-eventsourced-shopping-cart/docker-compose.yml
- samples/js-valueentity-shopping-cart/docker-compose.yml
- samples/valueentity-counter/docker-compose.yml
- sdk/config.json
- sdk/src/replicated-data/counter-map.js
- sdk/src/replicated-data/index.js
- sdk/src/replicated-data/iterators.js
- sdk/src/replicated-data/map.js
- sdk/src/replicated-data/multi-map.js
- sdk/src/replicated-data/register-map.js
- sdk/src/replicated-data/register.js
- sdk/src/replicated-data/set.js
- sdk/src/replicated-entity.js
- sdk/test/replicated-data/counter-map-test.js
- sdk/test/replicated-data/map-test.js
- sdk/test/replicated-data/multi-map-test.js
- sdk/test/replicated-data/register-map-test.js
- tck/src/replicated-entity.ts
Refs https://github.com/lightbend/akkaserverless-java-sdk/issues/48. Add specialised replicated maps for counters and registers, similar to Java SDK. Test with the new TCK tests from https://github.com/lightbend/akkaserverless-framework/pull/802 (needs to be published first, draft PR here). And support the new replicated maps from https://github.com/lightbend/akkaserverless-framework/pull/803. Refs https://github.com/lightbend/akkaserverless-java-sdk/issues/49.
> feat: add specialised replicated maps

- docs/Makefile
- docs/src/modules/javascript/nav.adoc
- docs/src/modules/javascript/pages/developer-tools.adoc
This PR:
- Moves the developer tools section from the main docs repo to this one
- Adds a variable for the minimum supported version of the SDK to show in the docs
> chore(docs): move developer tools to sdk repo

- codegen/js-gen-cli/src/it/resources/application.conf
- codegen/js-gen-cli/src/it/resources/scripts/setup.sh
- docs/src/modules/javascript/pages/developer-tools.adoc
- docs/src/modules/javascript/pages/index.adoc
- npm-js/README.md
- npm-js/create-akkasls-entity/README.md
- npm-js/create-akkasls-entity/template/base/README.md
- samples/js/js-eventsourced-shopping-cart/README.md
- samples/js/js-valueentity-shopping-cart/README.md
- samples/js/valueentity-counter/README.md
- samples/ts/ts-valueentity-shopping-cart/README.md
Fix usage of `NPM`, which should not be capitalised. Also some `YARN` and `YARM`.
> doc: fix references to npm

- sdk/package.json
Builds have started failing on protoc download for samples. See #184 and #187.
```
Error: invalid signature: 0x6d783f3c
at akkaserverless/javascript-sdk/main/samples/js/valueentity-counter/node_modules/unzipper/lib/parse.js:62:26
at tryCatcher (akkaserverless/javascript-sdk/main/samples/js/valueentity-counter/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (akkaserverless/javascript-sdk/main/samples/js/valueentity-counter/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (akkaserverless/javascript-sdk/main/samples/js/valueentity-counter/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (akkaserverless/javascript-sdk/main/samples/js/valueentity-counter/node_modules/bluebird/js/release/promise.js:61 …
```
> fix: pin node-fetch version for protoc download

- docs/Makefile
- docs/bin/bundle.sh
- samples/js/js-eventsourced-shopping-cart/proto/shoppingcart_api.proto
- samples/js/js-eventsourced-shopping-cart/proto/shoppingcart_domain.proto
- samples/js/js-eventsourced-shopping-cart/src/index.js
- samples/js/js-eventsourced-shopping-cart/src/shoppingcart.js
This PR:
- Adds bundling script and makefile target to create quickstart zip files (copied from the Java SDK)
- Adds antora tags to the JavaScript Event Sourced Shopping cart so it can be used in the quickstarts
> chore(docs): add bundles for quickstarts

- npm-js/create-akkasls-entity/template/base/Dockerfile
- samples/js/js-customer-registry/Dockerfile
- samples/js/js-customer-registry/package.json
- samples/js/js-eventsourced-shopping-cart/Dockerfile
- samples/js/js-eventsourced-shopping-cart/package.json
- samples/js/js-replicated-entity-example/Dockerfile
- samples/js/js-valueentity-shopping-cart/Dockerfile
- samples/js/js-valueentity-shopping-cart/package.json
- samples/js/js-views-example/Dockerfile
- samples/js/js-views-example/package.json
- samples/js/valueentity-counter/Dockerfile
- samples/js/valueentity-counter/package.json
- samples/ts/ts-customer-registry/Dockerfile
- samples/ts/ts-eventsourced-shopping-cart/Dockerfile
- samples/ts/ts-replicated-entity-example/Dockerfile
- samples/ts/ts-valueentity-counter/Dockerfile
- samples/ts/ts-valueentity-shopping-cart/Dockerfile
- samples/ts/ts-views-example/Dockerfile
- tck/Dockerfile
Refs https://github.com/lightbend/akkaserverless/issues/5016
If `npm start` (or other commands with `npm`) are used to start a service in a docker container, then when the pod is shutting down the SIGTERM received by `npm` is not propagated to the child process, but it's killed instead. This means the JS SDK doesn't get the SIGTERM for a graceful shutdown, and when it's killed there are unexpected stream closed errors in the proxy.
Looks like there a few ways to fix this. Have gone with calling `node` directly, rather than installing some init wrapper.
Have published a new version of the value entity shopping cart already:
```
gcr.io/akkaserverless-public/samples-js-value-entity-shopping-cart:0.0.3
```
> fix: graceful shutdown in docker builds

- docs/src/modules/javascript/pages/actions.adoc
- docs/src/modules/javascript/pages/eventsourced.adoc
- docs/src/modules/javascript/pages/index.adoc
- docs/src/modules/javascript/pages/kickstart.adoc
- docs/src/modules/javascript/pages/serialization.adoc
- docs/src/modules/javascript/pages/value-entity.adoc
- docs/src/modules/javascript/pages/views.adoc
Add supergroup and use `JavaScript` and `TypeScript` to get tab switching for all code snippets.
See https://github.com/lightbend/akkaserverless-docs/pull/952
> docs: add javascript/typescript supergroup for tabbed code snippets

- docs/src/modules/javascript/pages/developer-tools.adoc
- docs/src/modules/javascript/pages/kickstart.adoc
- npm-js/create-akkasls-entity/README.md
`npx` doesn't attempt to fetch a newer version if you have already one installed.
ref: https://github.com/npm/cli/issues/2329
> Use latest in npx commands

- docs/bin/bundle.sh
- samples/js/js-customer-registry/.bundleignore
- samples/js/js-eventsourced-shopping-cart/.bundleignore
- samples/ts/ts-customer-registry/.bundleignore
- samples/ts/ts-eventsourced-shopping-cart/.bundleignore
Didn't notice that #184 was missing the bundle ignore, so the sample zips can include `node_modules` and generated or compiled files. Have also excluded `package-lock.json` as some samples have this gitignored already.
> docs: add bundle ignores for build artifacts and generated code

- docs/src/modules/javascript/pages/call-another-service.adoc
- samples/js/js-doc-snippets/src/delegatingservice.js
- sdk/bin/prepare.sh
- sdk/index.d.preamble.ts
- sdk/package.json
- sdk/src/action.js
- sdk/src/event-sourced-entity.js
- sdk/src/grpc-util.jsdoc
- sdk/src/grpc-util.ts
- sdk/src/replicated-entity.js
- sdk/src/value-entity.js
Follow-up to #186. Try creating promisified gRPC clients automatically. A bit awkward to rebuild the package structure, and grpc-js doesn't export all of its types. Simplifies things a bit more on the user-side.
Haven't looked at the jsdoc types yet, or added this to other components.
> feat: provide promisified clients for inter-service calls

- sdk/package-lock.json
Updates for the vulnerability check:
```
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ OS Command Injection in ssh2                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ssh2                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ testcontainers                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ testcontainers > dockerode > docker-modem > ssh2             │ …
```
> bump: update ssh2 dependencies (security vulnerabilities)

- sdk/src/cloudevent.ts
- sdk/src/metadata.ts
- sdk/test/metadata.test.ts
When I originally wrote the JavaScript API, the important thing was that there was a very convenient way to access properties where you didn't have to deal with the fact that there could be multiple values for each property (beacuse usually there aren't). So I had a way of using the metadata as a plain JavaScript object/map. This API was not ported to TypeScript, which leaves the user experience somewhat lacking in my opinion.
This reinstates that.
Also, this reinstates the CloudEvents API which was inexplicably removed in #59 - it's always been a feature goal of Akka Serverless to support cloud standards, and CloudEvents is an important one of those considering we deal with events a lot.
> feat: reinstate metadata map and cloudevents

- samples/ts/ts-customer-registry/package-lock.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-eventsourced-shopping-cart/package-lock.json
- samples/ts/ts-eventsourced-shopping-cart/package.json
- samples/ts/ts-replicated-entity-example/package-lock.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-replicated-entity-shopping-cart/package-lock.json
- samples/ts/ts-replicated-entity-shopping-cart/package.json
- samples/ts/ts-valueentity-counter/package-lock.json
- samples/ts/ts-valueentity-counter/package.json
- samples/ts/ts-valueentity-shopping-cart/package-lock.json
- samples/ts/ts-valueentity-shopping-cart/package.json
- samples/ts/ts-views-example/package-lock.json
- samples/ts/ts-views-example/package.json
- sdk/package-lock.json
- sdk/package.json
Build in main start to fail because of silent update of grpc-js library. This only affecting TS compilation. 
```node
node_modules/@grpc/grpc-js/build/src/object-stream.d.ts:11:18 - error TS2430: Interface 'IntermediateObjectWritable<T>' incorrectly extends interface 'Writable'.
The types returned by 'end(...)' are incompatible between these types.
Type 'void' is not assignable to type 'this'.
'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.
```
Without this change, the grpc-js lib is bumped to 1.4.5 causing the error above.
> chore: fix version of @types/node to 14.18.3

- codegen/js-gen-cli/src/it/resources/application.conf
- samples/ts/ts-customer-registry/package-lock.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-eventsourced-shopping-cart/package-lock.json
- samples/ts/ts-eventsourced-shopping-cart/package.json
- samples/ts/ts-replicated-entity-example/package-lock.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-replicated-entity-shopping-cart/package-lock.json
- samples/ts/ts-replicated-entity-shopping-cart/package.json
- samples/ts/ts-valueentity-counter/package-lock.json
- samples/ts/ts-valueentity-counter/package.json
- samples/ts/ts-valueentity-shopping-cart/package-lock.json
- samples/ts/ts-valueentity-shopping-cart/package.json
- samples/ts/ts-views-example/package-lock.json
- samples/ts/ts-views-example/package.json
- sdk/package-lock.json
- sdk/package.json
We need this in order to use the new annotations in the Javascript SDK.
Draft because on top of #226.
Ready for review otherwise.
> chore: upgrade proxy to 0.8.5

- npm-js/create-akkasls-entity/template/base/docker-compose.yml
This adds commented out placeholders for configuring JWT dev secrets as implemented in https://github.com/lightbend/akkaserverless-framework/pull/1055.
> feat: placeholder configuration for JWT dev secrets

- .circleci/config.yml
Got some mail saying we need to do this before May.
> chore: Upgrade Circle-CI image to supported version

- docs/src/modules/javascript/pages/proto.adoc
No issue.  Just a fix for a small typo.
The doc renders the example with footnote 1 referring to the third line of:
```
rpc AddItem (AddLineItem) returns (google.protobuf.Empty) {
option (google.api.http) = {
post: "/cart/{cart_id}/items/add"
body: "*"
};
}
```
But the footnote says:
> This extra annotation specifies that you can call this endpoint using the POST method with the URI /cart/{user_id}/items/add, where {user_id} is the actual user id we want the cart for.
> Typo in proto.adoc

- samples/js/js-customer-registry/package-lock.json
- samples/js/js-customer-registry/package.json
- samples/js/js-doc-snippets/package-lock.json
- samples/js/js-doc-snippets/package.json
- samples/js/js-eventsourced-shopping-cart/package.json
- samples/js/js-replicated-entity-example/package.json
- samples/js/js-replicated-entity-shopping-cart/package-lock.json
- samples/js/js-replicated-entity-shopping-cart/package.json
- samples/js/js-valueentity-shopping-cart/package.json
- samples/js/js-views-example/package-lock.json
- samples/js/js-views-example/package.json
- samples/js/valueentity-counter/package.json
- samples/ts/ts-customer-registry/package-lock.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-eventsourced-shopping-cart/package-lock.json
- samples/ts/ts-eventsourced-shopping-cart/package.json
- samples/ts/ts-replicated-entity-example/package-lock.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-replicated-entity-shopping-cart/package-lock.json
- samples/ts/ts-replicated-entity-shopping-cart/package.json
- samples/ts/ts-valueentity-counter/package-lock.json
- samples/ts/ts-valueentity-counter/package.json
- samples/ts/ts-valueentity-shopping-cart/package-lock.json
- samples/ts/ts-valueentity-shopping-cart/package.json
- samples/ts/ts-views-example/package-lock.json
- samples/ts/ts-views-example/package.json
Refs #247. Run `samples/bin/update.sh` to update samples to `0.33.4` and other latest versions.
> chore: update versions in samples

- docs/src/modules/javascript/examples/action/src/action.js
- docs/src/modules/javascript/examples/action/src/action.ts
- docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.js
- docs/src/modules/javascript/examples/test/eventsourced/shoppingcart.ts
- docs/src/modules/javascript/examples/value-entity/src/shoppingcart.js
- docs/src/modules/javascript/examples/value-entity/src/shoppingcart.ts
- samples/ts/ts-valueentity-counter/test/testkit.ts
- sdk/integration-test/integration-testkit-test.js
- sdk/src/action-support.js
- sdk/src/command-helper.js
- sdk/src/context-failure.ts
- sdk/src/reply.ts
- sdk/test/example.proto
- sdk/test/reply.test.ts
This allows setting a custom status when failing, by adding an optional status parameter to the `ctx.fail()` and `replies.failure()` methods.
> feat: allow specifying a custom status when failing

- sdk/src/metadata.ts
This provides a helper for setting a custom HTTP status code, for when HTTP transcoding is being used and a custom status code is required.
> feat: helper for setting custom HTTP status code

- npm-js/akkasls-scripts/bin/download-codegen.js
Previously was 404ing causing the entire install process to fail
> Fix windows install path for codegen executable

- sdk/src/integration-testkit.ts
Fixes #265.
I'm hoping this will fix an unhandled error on testkit shutdown. I believe there is a race condition, the proxy container gets shutdown, and then immediately after the SDK will be shutdown. This will cause the connections between the two to close, but the proxy container might attempt to reconnect. This I think triggers TestContainers to throw an uncaught exception, which mocha fails on.
So, we have to wait for the proxy container to shutdown before shutting down the SDK, to ensure it won't attempt to reconnect.
> fix: unhandled error on testkit shutdown

- sdk/index.js
- sdk/src/metadata.jsdoc
- sdk/src/view-support.js
The metadata module was being exported in place of just the Metadata class. Also make the entries parameter optional with default empty array in the jsdoc type declaration.
Metadata tests import directly from the source file, and Metadata is not used in the samples (which do use the SDK), so not currently covered by tests. Suggests that being able to import the SDK exports in the tests would be useful — these go through some processing though, given the current setup. Could also extend a sample to make use of metadata. Just manually verified for now.
> fix: metadata export and default empty entries

- samples/js/js-valueentity-shopping-cart/package.json
0.0.3 is still on the old protocol, might be nice to
have them separate
> Update js-valueentity-shopping-cart version to 0.0.4

- sdk/index.js
- sdk/src/akkaserverless.jsdoc
- sdk/src/akkaserverless.ts
- sdk/src/reply.jsdoc
- sdk/src/reply.ts
- sdk/test/reply.test.ts
Will also need a forward port to the rename-branch
Note that in addition to making the `GrpcStatus` enum public in TS this also moved it from `akkaserverless.replies.GrpcStatus` directly to `akkaserverless.GrpcStatus`
> fix: Status code was not accessible from typescript #284

- sdk/src/cloudevent.jsdoc
- sdk/src/jwt-claims.jsdoc
- sdk/src/metadata.jsdoc
This continues work from #286, adding Typescript type info for other features that have been added.
> Added additional types for Typescript

- sdk/bin/prepare.sh
- sdk/package-lock.json
- sdk/package.json
- sdk/src/protobuf-any.jsdoc
- sdk/src/protobuf-any.ts
- sdk/src/protobuf-helper.ts
- sdk/test/protobuf-any-test.ts
Refs #293. Breaking up into smaller steps. Only targeting `kalix-main` for this.
Convert the protobuf any support and tests to TypeScript. Direct translation, just add typing.
> chore: convert protobuf support to TypeScript

- sdk/src/effect-serializer.ts
- sdk/src/effect.ts
- sdk/src/kalix.ts
- sdk/src/metadata.ts
- sdk/test/effect-serializer-test.ts
Refs #293. Draft, builds on #294. 
Convert effect serializer and test directly over to TypeScript.
> chore: convert effect serializer to TypeScript

- samples/ts/ts-replicated-entity-shopping-cart/src/shoppingcart.ts
- sdk/bin/compile-protobuf.sh
- sdk/src/event-sourced-entity.ts
- sdk/src/replicated-data/counter-map.ts
- sdk/src/replicated-data/map.ts
- sdk/src/replicated-data/multi-map.ts
- sdk/src/replicated-data/register-map.ts
- sdk/src/replicated-data/register.ts
- sdk/src/replicated-data/set.ts
- sdk/src/serializable.ts
- sdk/test/replicated-data/counter-map-test.ts
- sdk/test/replicated-data/map-test.ts
- sdk/test/replicated-data/multi-map-test.ts
- sdk/test/replicated-data/register-map-test.ts
- sdk/test/replicated-data/register-test.ts
- sdk/test/replicated-data/set-test.ts
- tck/src/replicated-entity.ts
Refs #320.
Make replicated data types generic. Replicated entity state is not yet generic, so this is just the underlying step towards that. Entities may need a bit of reworking to have this ripple through the contexts in particular.
The typing for serialized state is still awkward in TypeScript, with it requiring the reflective Message type, but should be able to improve on this and use the generated protobuf directly (see #326).
The type parameters will default to `Serializable` to have the same behaviour as before. Some tests are updated, others left as is.
Note that this used single letter type parameters at first (`T`, `E`, `K`, `V` and so on), but the latest TypeScript docs are now using full names, so I've followed the full name convention here as well.
> feat: make replicated data types generic

- build/license.json
- samples/ts/ts-customer-registry/src/customer-event-sourced-entity.ts
- samples/ts/ts-customer-registry/src/customer-value-entity.ts
- samples/ts/ts-eventsourced-shopping-cart/src/shoppingcart.ts
- samples/ts/ts-eventsourced-shopping-cart/test/testkit.ts
- samples/ts/ts-valueentity-counter/src/counter.ts
- samples/ts/ts-valueentity-counter/test/testkit.ts
- sdk/index.ts
- sdk/src/reply.ts
- sdk/test/reply.test.ts
- tck/src/action.ts
- tck/src/event-sourced-entity.ts
- tck/src/value-entity.ts
Refs #320 (and rather than do all type improvements in one go, breaking it up into different areas).
Make `Reply` generic over its message type, to be able to type the responses for handlers. Type parameter defaults to `any` so that untyped is still supported.
Also re-export `Reply` from top-level and add the reply factory functions as static methods to `Reply` — which I think feels more natural for factory methods. And simplifies it slightly compared with prefixing with the `replies` namespace. Old approach still supported as well.
Some samples and tests are updated to use the generic Reply and methods, others left as is for old approach.
We could also create the same API as for Java/Scala SDKs, but that would either be a breaking a change, or probably odd to have both `Reply.message` …
> feat: make Reply generic over message type

- sdk/src/kalix.ts
Forward headers for actions was broken. Looks like this line was inadvertently removed in #269 with the renaming.
Must be missing tests for this. As it's part of the SDK protocol, probably useful to have it in the TCK.
> fix: set component settings for actions

- README.md
- docs/Makefile
- npm-js/create-kalix-entity/template/base/README.md
- samples/js/js-replicated-entity-example/package.json
- samples/js/js-views-example/package.json
- sdk/package.json
`SDK SDK` was introduced at some point in the renaming
> rename: fix 'SDK SDK' typo

- sdk/src/event-sourced-entity.ts
- sdk/src/value-entity.ts
- sdk/typedoc.json
Tweak the typedoc settings a little.
Skip the readme page (which just links to the main docs anyway) and go straight to the index page.
Use source order sorting. This order is usually meaningful in each source file, so could be better to read in the API docs, rather than just alphabetical.
Warn on invalid links. A few links were actually invalid for typedoc (while valid for vscode).
Warnings to errors, to fail on missing exports or invalid links.
> chore: tweak typedoc settings

- docs/bin/bundle.sh
Follow-up to #339. Make sure the testkit version is updated when creating bundles on release.
> docs: update the testkit version in bundle downloads

- codegen/js-gen/src/main/scala/io/kalix/codegen/js/EntityServiceSourceGenerator.scala
- codegen/js-gen/src/test/scala/io/kalix/codegen/js/EntityServiceSourceGeneratorSuite.scala
- samples/js/js-eventsourced-shopping-cart/test/shoppingcart.test.js
- samples/js/js-valueentity-shopping-cart/test/shoppingcart.test.js
- samples/js/valueentity-counter/test/counter.test.js
- samples/ts/ts-eventsourced-shopping-cart/test/shoppingcart.test.ts
- samples/ts/ts-valueentity-counter/test/counter.test.ts
- samples/ts/ts-valueentity-shopping-cart/test/shoppingcart.test.ts
- testkit/example/proto/example.proto
- testkit/example/types/event-sourced-entity.d.ts
- testkit/example/types/value-entity.d.ts
- testkit/package-lock.json
- testkit/src/mock-event-sourced-entity.ts
- testkit/src/mock-value-entity.ts
- testkit/test/mock-event-sourced-entity.test.ts
- testkit/test/mock-value-entity.test.ts
Entity command handlers can already be async. Add support for this to the codegen and testkit.
Testkit hasn't been published yet, so not exactly breaking, but `handleCommand` in the mock entities is now async. If we wanted to make it compatible with what was there before, we could also have two versions of mocked command handling, where the sync version throws if the command handler returns a Promise. But simpler to just have one method, explicitly async.
> fix: support async command handlers in codegen and testkit

- codegen/build.sbt
- npm-js/kalix-scripts/bin/download-codegen.js
- sdk/bin/download-protoc.js
Refs #99.
I don't have an M1 mac to try this out on, but trying out some updates.
Bump protoc to a version which has an `osx-aarch_64` download. Not strictly needed if running the x86 version with rosetta works anyway.
Bump `nativeImageVersion` for building locally. Should automatically download an M1-compatible graalvm.
CircleCI doesn't support M1 runners yet, so we can't automatically publish the codegen binaries. Use the x86 download with rosetta instead for now.
@johanandren, can you check whether this works? We can also make a release if it's easier to test in a sample properly.
> bump: updates for apple silicon

- testkit/package.json
Testkit didn't have its version updated on publish (and published 0.0.0 instead). Can publish a `1.0.0-M9` manually.
> build: fix testkit published version

- npm-js/kalix-scripts/bin/kalix-scripts.js
Refs #99.
Still to be tested on an M1... may be easier to test fully once released, but can be checked locally.
> fix: support docker build on arm64 in kalix-scripts

- npm-js/create-kalix-entity/template/base-js/package.json
- npm-js/create-kalix-entity/template/base-ts/package.json
Not sure why `jsdoc` and `uglify-js` were listed as dependencies in the templates, but shouldn't be needed as explicit dependencies.
> chore: remove unnecessary dependencies from templates

- npm-js/create-kalix-entity/template/base-js/Dockerfile
- npm-js/create-kalix-entity/template/base-ts/Dockerfile
- samples/js/js-doc-snippets/Dockerfile
- samples/js/js-eventsourced-shopping-cart/Dockerfile
- samples/js/js-replicated-entity-shopping-cart/Dockerfile
- samples/js/js-valueentity-shopping-cart/Dockerfile
- samples/js/valueentity-counter/Dockerfile
- samples/ts/ts-eventsourced-shopping-cart/Dockerfile
- samples/ts/ts-replicated-entity-shopping-cart/Dockerfile
- samples/ts/ts-valueentity-counter/Dockerfile
- samples/ts/ts-valueentity-shopping-cart/Dockerfile
Not sure if there was a reason to use an exact version, other than just avoiding downloading new images when published. Latest for 14 is `14.19.3`. Could also just use the `node:14-buster-slim` image. Updated to the `14.19` tag as a compromise.
> bump: update node docker image to 14.19

- docs/src/modules/javascript/pages/kickstart.adoc
Follow-up to #363. Did start updating the kalix docs theme to allow nested tabs, but it's a bit awkward. Change this one use of nested tabs to instead just have a nested note for the TypeScript variant.
> docs: avoid nested tabs, nest note instead

- npm-js/kalix-scripts/bin/kalix-scripts.js
References #99
Follow up to #365
> fix: Docker cross build not installed unless explicitly '--load'ed 

- codegen/core/src/main/scala/io/kalix/codegen/DescriptorSet.scala
- codegen/js-gen-cli/src/main/scala/io/kalix/codegen/js/Cli.scala
- codegen/js-gen/src/main/scala/io/kalix/codegen/js/SourceGenerator.scala
- codegen/js-gen/src/test/scala/io/kalix/codegen/js/SourceGeneratorSuite.scala
Refs #235. Allow the new codegen annotation to be used (just missing extension registration). There are no tests for this yet, but currently trying it out in updated quickstarts.
> fix: enable codegen with new annotation

- codegen/js-gen/src/main/scala/io/kalix/codegen/js/EntityServiceSourceGenerator.scala
- codegen/js-gen/src/test/scala/io/kalix/codegen/js/EntityServiceSourceGeneratorSuite.scala
- codegen/js-gen/src/test/scala/io/kalix/codegen/js/TestData.scala
For event sourced entity codegen, also generate the type lookups for events. These reflective types have to be used for any persisted messages (as only the reflective protobuf has the message name for the Any type url).
Added as an improvement for quickstart docs: https://github.com/lightbend/kalix-docs/pull/1402
> feat: generate type lookups for events

- .circleci/config.yml
- testkit/package-lock.json
- testkit/package.json
This should avoid the build failures on testkit publish by always building against a local snapshot of the SDK. For when the testkit has been updated and depends on corresponding changes in the SDK.
> build: update testkit publishing

- .circleci/config.yml
- docs/Makefile
- docs/config/validate-links.json
- docs/dev/src/modules/ROOT/partials/include.adoc
- docs/src/modules/javascript/pages/quickstart/cr-value-entity-javascript.adoc
- samples/js/js-customer-registry-quickstart/.bundleignore
- samples/js/js-customer-registry-quickstart/.dockerignore
- samples/js/js-customer-registry-quickstart/.gitignore
- samples/js/js-customer-registry-quickstart/Dockerfile
- samples/js/js-customer-registry-quickstart/README.md
- samples/js/js-customer-registry-quickstart/docker-compose.yml
- samples/js/js-customer-registry-quickstart/integration-test/customer.test.js
- samples/js/js-customer-registry-quickstart/jsconfig.json
- samples/js/js-customer-registry-quickstart/package.json
- samples/js/js-customer-registry-quickstart/proto/customer_api.proto
- samples/js/js-customer-registry-quickstart/proto/customer_domain.proto
- samples/js/js-customer-registry-quickstart/proto/kalix_policy.proto
- samples/js/js-customer-registry-quickstart/src/customer.js
- samples/js/js-customer-registry-quickstart/src/index.js
- samples/js/js-customer-registry-quickstart/test/customer.test.js
The current customer registry sample includes more than needed for the quickstart (has both value entity and event sourced entity versions) and is not set up for being a usable and runnable download. The quickstart docs for this sample (currently in the main docs) are outdated, use line numbers for code samples, and don't use the codegen.
Update things in line with the customer registry quickstarts for JVM SDKs.
Create a new version of the customer registry sample for the quickstart, based on the template and using codegen, with tests, and its own quickstart-friendly README. The quickstart bundle is tested in CI. This is a new customer registry sample, with the old one unchanged (still referenced by the main docs), and the old sample can be updated later (like in the JVM SDKs).
Add a new …
> docs: add new quickstart for customer registry in javascript

- .github/release-issue-template.md
Not needed now. Latest version provided by the SDK docs and updated automatically on publish.
> chore: remove version update from release template

- docs/src/modules/developing/pages/development-process-js.adoc
Link validation failing as the quickstarts are not in the main docs.
Not sure the quickstart is best for a general docker packaging and deploying, but just correcting the link for now.
> docs: fix links to quickstart from dev process page

- .circleci/config.yml
Latest proxy docker images (on temurin 17) are not usable on older docker. Update the machine image for CircleCI to get newer versions of everything. I'll manually check this.
> ci: update machine image

- sdk/src/kalix.ts
- sdk/test/kalix.test.ts
Refs https://github.com/lightbend/kalix-proxy/issues/1566. Builds on #392.
> fix: add severity to user function error reporting

- npm-js/kalix-scripts/bin/download-codegen.js
- npm-js/kalix-scripts/package-lock.json
- npm-js/kalix-scripts/package.json
Refs #394
Switch over to axios, which gets the disconnected signals. And use `stream.pipeline` which adds error handling to the stream automatically (otherwise it's adding event handlers for `error` and `aborted` on the response data, and `close` on the writer for resolving successfully).
This just logs the error currently, on disconnected streams. Looks like this
```
Fetching kalix-codegen-js from https://repo.lightbend.com/raw/kalix/versions/1.0.0/kalix-codegen-js-x86_64-apple-darwin
Saving to .../kalix-scripts/bin/kalix-codegen-js.bin
Failed to download Kalix codegen binary: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
at new NodeError (internal/errors.js:322:7)
at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
at IncomingMessage.emit (events.js:400:28)
at …
```
> fix: handle disconnected streams on codegen download

- npm-js/kalix-scripts/package-lock.json
- npm-js/kalix-scripts/package.json
- package-lock.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-views-example/package.json
- sdk/package.json
- tck/package.json
- testkit/package-lock.json
- testkit/package.json
References #398
Not yet a fix, but workaround for now. 
I'm not sure if I got if in all places we will need. Let's see what CI will tells us.
> chore: stick to protobufjs 6.11.3 (for now)

- .circleci/config.yml
* downgrade ubuntu images from 22.04 to latest 20.04
* upgrade macos image to 12.5.1
Fixes following the 1.0.1 release (#402).
Codegen binary for linux was built against a newer glibc (building with ubuntu 22.04) than in the docker image (debian 10). The Debian 11 (node bullseye) images are still on older glibc as well. To keep things simple, downgrade the machine images to ubuntu 20.04 again, but should still be with a new enough docker version (the reason they were bumped originally, #391).
The 1.0.1 release failed to build the macOS codegen binary, as 12.5.0 image was not available. Bump to available 12.5.1.
I'll manually confirm a couple of things in the test build.
Would be useful to have some tests that build these, and check across platforms, but for another time...
> ci: update machine images

- sdk/src/kalix.ts
References https://github.com/lightbend/kalix-proxy/issues/1469 and depends on https://github.com/lightbend/kalix-proxy/pull/1599
> chore: avoiding calling through the mesh to same services components

- codegen/js-gen-cli/src/it/resources/application.conf
- npm-js/create-kalix-entity/template/base-common/docker-compose.yml
- samples/js/js-customer-registry-quickstart/docker-compose.yml
- samples/js/js-doc-snippets/docker-compose.yml
- samples/js/js-eventsourced-shopping-cart/docker-compose.yml
- samples/js/js-replicated-entity-shopping-cart/docker-compose.yml
- samples/js/js-shopping-cart-quickstart/docker-compose.yml
- samples/js/js-valueentity-shopping-cart/docker-compose.yml
- samples/js/valueentity-counter/docker-compose.yml
- samples/ts/ts-customer-registry-quickstart/docker-compose.yml
- samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml
- samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml
- samples/ts/ts-shopping-cart-quickstart/docker-compose.yml
- samples/ts/ts-valueentity-counter/docker-compose.yml
- samples/ts/ts-valueentity-shopping-cart/docker-compose.yml
- sdk/config.json
References [Proxy 1.0.16](https://github.com/lightbend/kalix-proxy/issues/1611)
> chore: upgrade kalix proxy version to 1.0.16

- sdk/src/index.ts
- sdk/src/kalix.ts
This increases the gRPC maximum receive message size to 12MB, and also makes both it and the max send size configurable.
> feat: increase max receive message size

- sdk/package-lock.json
Build is failing https://app.circleci.com/pipelines/github/lightbend/kalix-javascript-sdk/1370/workflows/52ebe57d-137d-4763-ba2e-a17a2e17bf1b/jobs/8737?invite=true#step-106-3
This PR fixes it.
```
#!/bin/bash -eo pipefail
npm audit --production
npm WARN config production Use `--omit=dev` instead.
minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix`
node_modules/minimatch
1 high severity vulnerability
To address all issues, run:
npm audit fix
Exited with code exit status 1
```
> chore: bump minimatch version due to vulnerability alert

- .circleci/config.yml
Fix #433 
I could not test this locally to confirm which curl version is included but upgraded to latest ubuntu version which is very likely to contain the required curl version `7.76.0`.
I know we are already using this ubuntu version in other places. Let me know if you think this is a bad idea.
> fix: avoid failing silently when publishing codegen

- npm-js/create-kalix-entity/template/base-ts/package.json
- samples/ts/ts-customer-registry-quickstart/package.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-eventsourced-shopping-cart/package.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-replicated-entity-shopping-cart/package.json
- samples/ts/ts-shopping-cart-quickstart/package.json
- samples/ts/ts-valueentity-counter/package.json
- samples/ts/ts-valueentity-shopping-cart/package.json
- samples/ts/ts-views-example/package.json
Looking to fix the typescript issue as seen in #437 by allowing an updated `@types/node` dependency.
> fix: allow updated type dependency for node

- bin/update-proxy-versions.sh
Adding this script so we can use it later in automating the proxy release a bit more. For now, it can be used manually anyway.
References https://github.com/lightbend/kalix-proxy/issues/967
> ci: add script to bump proxy version

- docs/dev/src/modules/ROOT/partials/grpc/using-acls.adoc
- docs/src/modules/javascript/pages/access-control.adoc
References https://github.com/lightbend/kalix-docs/issues/1665
Dependent on https://github.com/lightbend/kalix-docs/pull/1670
> docs: add grpc common ACL docs to sdk specific page

- sdk/src/kalix.ts
For example if it is not defined, or overloaded with broken logic.
References lightbend/kalix-proxy#1570
> fix: Catch and continue discovery if component.preStart fails

- docs/Makefile
- sdk/src/kalix.ts
References #389
Depends on upstream support for the typescript name in the proxy that must be in production before this can be merged/released.
> chore: Report ts and js as separate SDKs #389

- codegen/build.sbt
- codegen/project/plugins.sbt
FOSSA is complaining about this so I thought we could make it happier.
> chore: upgrade scala version to 2.13.10

- docs/src/modules/javascript/pages/views.adoc
Refs https://github.com/lightbend/kalix-proxy/issues/1207
Add details for dropping obsolete view data under the how to modify a view section.
> docs: drop obsolete view data

- docs/dev/antora.yml
Reverts #482 
These settings are used when building the docs locally in dev mode. Something else is enabling this in prod.
> fix: re-enable todos in dev

- CONTRIBUTING.md
We have already moved to 18 (see #459), but contributing file was not updated.
> chore: use node 18 instead

- .circleci/config.yml
- sdk/package-lock.json
- sdk/package.json
Resolves #502. Resolves https://github.com/lightbend/kalix/issues/9437.
Fix was only available in protobufjs 7 before, but there's a new 6.11 patch release with the fix now.
Bumping to 7 will be more work, see:  https://github.com/lightbend/kalix-javascript-sdk/issues/502#issuecomment-1643060410.
Doesn't seem to be a tagged release for 6.11.4, but released from:
https://github.com/protobufjs/protobuf.js/commits/release-6.11.4
> bump: update protobufjs to 6.11.4

- npm-js/create-kalix-entity/template/base-js/Dockerfile
- npm-js/create-kalix-entity/template/base-ts/Dockerfile
- samples/js/js-customer-registry-quickstart/Dockerfile
- samples/js/js-customer-registry/Dockerfile
- samples/js/js-doc-snippets/Dockerfile
- samples/js/js-eventsourced-shopping-cart/Dockerfile
- samples/js/js-replicated-entity-example/Dockerfile
- samples/js/js-replicated-entity-shopping-cart/Dockerfile
- samples/js/js-shopping-cart-quickstart/Dockerfile
- samples/js/js-valueentity-shopping-cart/Dockerfile
- samples/js/js-views-example/Dockerfile
- samples/js/valueentity-counter/Dockerfile
- samples/ts/ts-customer-registry-quickstart/Dockerfile
- samples/ts/ts-customer-registry/Dockerfile
- samples/ts/ts-eventsourced-shopping-cart/Dockerfile
- samples/ts/ts-replicated-entity-example/Dockerfile
- samples/ts/ts-replicated-entity-shopping-cart/Dockerfile
- samples/ts/ts-shopping-cart-quickstart/Dockerfile
- samples/ts/ts-valueentity-counter/Dockerfile
- samples/ts/ts-valueentity-shopping-cart/Dockerfile
- samples/ts/ts-views-example/Dockerfile
- tck/Dockerfile
Bumping the dockerfiles to node 18 was missed in #459. Drop the minor version to keep maintaining this simple.
Also bump the debian version from debian 10 (buster) to current stable debian 12 (bookworm). This is required, as the CI images were updated to ubuntu 22.04 in #434, and the published codegen native images now require a newer glibc. See #406 for when this was downgraded again for this reason. We could also switch the codegen native image builds for linux to static binaries to avoid this issue on dynamically linking libc.
> bump: update node base image in Dockerfiles to 18-bookworm-slim

- npm-js/kalix-scripts/package-lock.json
- npm-js/kalix-scripts/package.json
- samples/ts/ts-customer-registry/package-lock.json
- samples/ts/ts-customer-registry/package.json
- samples/ts/ts-replicated-entity-example/package-lock.json
- samples/ts/ts-replicated-entity-example/package.json
- samples/ts/ts-views-example/package-lock.json
- samples/ts/ts-views-example/package.json
- tck/package.json
- testkit/package-lock.json
- testkit/package.json
Follow-up to #504. While that fixed the audit check, we pinned protobufjs versions in other places in #401. Update all of these to protobufjs 6.11.4.
> bump: update protobufjs to 6.11.4 (everywhere)

- .circleci/config.yml
We sometimes see the native image build fail with out-of-memory for `npm-js-tests`. For successful builds it's reaching 97% memory usage, and can sometimes go over the limit. The default resource class is 4 GB. Upgrade to the `large` resource class with 8 GB.
> ci: upgrade resources for npm-js-tests to large for native image

- .circleci/config.yml
Refs #511. Bump to `macos.x86.medium.gen2`, as default `medium` class will be deprecated on 2 October.
> ci: bump macos resource class to medium gen2

- .github/release-issue-template.md
- docs/src/modules/javascript/pages/kickstart.adoc
- npm-js/create-kalix-entity/template/base-common/README.md
- samples/js/js-customer-registry-quickstart/README.md
- samples/js/js-eventsourced-shopping-cart/README.md
- samples/js/js-replicated-entity-shopping-cart/README.md
- samples/js/js-shopping-cart-quickstart/README.md
- samples/js/js-valueentity-shopping-cart/README.md
- samples/js/valueentity-counter/README.md
- samples/ts/ts-customer-registry-quickstart/README.md
- samples/ts/ts-eventsourced-shopping-cart/README.md
- samples/ts/ts-replicated-entity-shopping-cart/README.md
- samples/ts/ts-shopping-cart-quickstart/README.md
- samples/ts/ts-valueentity-counter/README.md
- samples/ts/ts-valueentity-shopping-cart/README.md
Refs: #532, lightbend/kalix-docs#2018
> docs: fix more broken links to Setting Up section

- docs/src/modules/javascript/pages/access-control.adoc
- docs/src/modules/javascript/pages/index.adoc
- docs/src/modules/javascript/pages/quickstart/cr-value-entity-javascript.adoc
- docs/src/modules/javascript/pages/quickstart/cr-value-entity-typescript.adoc
- docs/src/modules/javascript/pages/quickstart/sc-eventsourced-entity-javascript.adoc
- docs/src/modules/javascript/pages/quickstart/sc-eventsourced-entity-typescript.adoc
- samples/js/js-customer-registry-quickstart/README.md
- samples/js/js-shopping-cart-quickstart/README.md
- samples/ts/ts-customer-registry-quickstart/README.md
- samples/ts/ts-shopping-cart-quickstart/README.md
> docs: rename Quickstarts to Samples

- codegen/js-gen-cli/src/it/resources/application.conf
- npm-js/create-kalix-entity/template/base-common/docker-compose.yml
- samples/js/js-customer-registry-quickstart/docker-compose.yml
- samples/js/js-customer-registry/docker-compose.yml
- samples/js/js-doc-snippets/docker-compose.yml
- samples/js/js-eventsourced-shopping-cart/docker-compose.yml
- samples/js/js-replicated-entity-example/docker-compose.yml
- samples/js/js-replicated-entity-shopping-cart/docker-compose.yml
- samples/js/js-shopping-cart-quickstart/docker-compose.yml
- samples/js/js-valueentity-shopping-cart/docker-compose.yml
- samples/js/js-views-example/docker-compose.yml
- samples/js/valueentity-counter/docker-compose.yml
- samples/ts/ts-customer-registry-quickstart/docker-compose.yml
- samples/ts/ts-customer-registry/docker-compose.yml
- samples/ts/ts-eventsourced-shopping-cart/docker-compose.yml
- samples/ts/ts-replicated-entity-example/docker-compose.yml
- samples/ts/ts-replicated-entity-shopping-cart/docker-compose.yml
- samples/ts/ts-shopping-cart-quickstart/docker-compose.yml
- samples/ts/ts-valueentity-counter/docker-compose.yml
- samples/ts/ts-valueentity-shopping-cart/docker-compose.yml
- samples/ts/ts-views-example/docker-compose.yml
- sdk/config.json
- testkit/src/integration-testkit.ts
> Bump: runtime 1.1.30
